Fix flags

diff --git a/githooks/pre-push b/githooks/pre-push
--- a/githooks/pre-push
+++ b/githooks/pre-push
@@ -2,8 +2,10 @@
 
 if [[ $1 == "prod" ]]; then
 echo "Pre-push hook: build and push Docker image"
+set -e # Fail whole command if one fail
 docker-compose build
 docker-compose push
+set +e
 else
 echo "No docker build as not pushing to prod"
 fi;
